#!/usr/bin/env python3
print("Content-type: text/html\n")
print('<html>')
print('<head>')
print('<meta charset="utf-8">')
print('</head>')
print('<body>')
print('<form enctype="multipart/form-data" action="worker.py" method="post">')
print('<p>Файл xls: <input type="file" name="file0" accept="application/vnd.ms-excel" /></p>')
print('<p>Файл ods: <input type="file" name="file1" accept="application/vnd.oasis.opendocument.spreadsheet"/></p>')
print('<p><input type="submit" value="Загрузить" /></p>')
print('</form>')
print('</body>')
print('</html>')
